---
- name: General Config
  gather_facts: false
  hosts: switches
  tasks:

  - name: show run
    ios_command:
      commands:
        - show run
      host: "{{ ansible_host }}"
      username: developer
      password: C1sco12345
    register: config
  - debug:
     var: config

  - name: save output to /var/lib/awx/projects
    copy:
      content: "{{ config.stdout[0] }}"
      dest: "/backup/show_run_{{ inventory_hostname }}.txt"
    
 

