---
- name: General Config
  gather_facts: false
  hosts: Routers
  tasks:

  - name: show run
    ios_command:
      commands:
        - show run
      host: "{{ ansible_host }}"
      username: developer
      password: C1sco12345
    register: config
  - debug:
     var: config

  - name: save output to /home/anjali/backup
    copy:
      content: "{{ config.stdout[0] }}"
      dest: "/home/backup/show_run_{{ inventory_hostname }}.txt"
- name: notify_slack
  hosts: localhost
  gather_facts: no
  connection: local
  tasks:
  - name: "notify operations_channel"
    slack:
      token: T01MPG3CTSR/B020TKE481Y/2eNlrivvB5E3IyRN0mxMD9jb
      msg: 'Backup has been taken place successfully'
      channel: '#operations_ansible'
    delegate_to: localhost
